### ISSUE TITLE
Bioconductor review

### ISSUE THREAD

**Issue by jimhester** [road2stat/sbgr#15] opened 2015-08-14 18:10 UTC
Nan and Tengfei,

Overall this looks like a well written straightforward package that I would
gladly accept into Bioconductor with the below suggestions.  Thank for your
patience with the review process and I apologize for the delay in reviewing
this package.
- Rather than supplying a token argument for every function (and checking if it
  exists) consider writing an `authenticate()` function, which stores the token
  in an environment within the package and a corresponding get function which
  will provide an appropriate error message if no token is provided. i.e.

``` r
.token <- new.env(parent = emptyenv())

get_token <- function() {
  token <- .token$token
  if (is.null(token)) {
    stop("Please authenticate with ",
        sQuote("authenticate()"),
        " or provide an ",
        sQuote("auth_token"))
  }
}

#' @export
authenticate <- function(auth_token) {

  # maybe make a request to check if the token is valid here?

  .token$token <- auth_token
}

# example for upload_info
upload_info = function (auth_token = get_token(), upload_id = NULL) {

    req = sbgapi(auth_token = auth_token,
                 path = paste0('upload/multipart/', upload_id),
                 method = 'GET')

    status_check(req)
}
```
- Explicit returns at the end of functions are superfluous (and actually slower),
  so it is best to just return the object directly.  The only time you need
  an explicit return is when returning before the function's end.
- if a parameter can take a enumerated number of values I would suggest you use
  `match.args()` and a switch statement.  This will provide you with error
  checking of the arguments and partial matching, and make the code more clear.

e.g.

``` r
sbgapi <- function(method = c('GET', 'POST', 'PUT', 'DELETE')) {

    method <- match.args(method)

    switch(method,
      GET = {
         GET()
      },
      POST = {
        #validation code
        POST()
      }
    )
}
```

In addition for the `sbgapi()` function because every method returns a request
response and the switch is the last statement in the function you don't need to
save them to a variable at all, just use the implicit return from the switch.
- A number of the files contained trailing whitespace characters
  throughout the project.  While these characters do not affect the execution of
  the code, they are unnecessary.  You can use the following one liner to strip them
  out `find . -type f -not -path './.git/*' -exec perl -i -pe 's/ +$//' {} \;`.
  I would also suggest turning on `visible whitespace` in your editor of choice
  so you can easily spot this in the future.
- In `file_meta_update()` You use `if (is.null(project_id) | is.null(file_id))`,
  when doing logical comparisons of 1 element vectors it is better to use `||`
  rather than the vectorized `|`.

Thank you again for the submission and your patience.  Let me know if you have
any further questions at (https://tracker.bioconductor.org/issue1264). I have
cross posted this response to your GitHub Issue tracker for convenience
(https://github.com/road2stat/sbgr/issues/15).

-Jim

**Comment by tengfei** [comment] 2015-08-14 18:31
On Fri, Aug 14, 2015 at 2:10 PM, Jim Hester notifications@github.com
wrote:

> Nan and Tengfei,
> 
> Overall this looks like a well written straightforward package that I would
> gladly accept into Bioconductor with the below suggestions. Thank for your
> patience with the review process and I apologize for the delay in reviewing
> this package.
> - Rather than supplying a token argument for every function (and
>   checking if it exists) consider writing an authenticate() function,
>   which stores the token in an environment within the package and a
>   corresponding get function which will provide an appropriate error message
>   if no token is provided. i.e.
> 
> .token <- new.env(parent = emptyenv())
> get_token <- function() {
>   token <- .token$token
>   if (is.null(token)) {
>     stop("Please authenticate with ",
>         sQuote("authenticate()"),
>         " or provide an ",
>         sQuote("auth_token"))
>   }
> }
> #' @exportauthenticate <- function(auth_token) {
> 
>   # maybe make a request to check if the token is valid here?
> 
>   .token$token <- auth_token
> }
> 
> Thanks a lot Jim!  and thanks for all the suggestions!

Please check the branch easy_api on git, the 99.*.R file, I created a
higher level API for end users and a second vignette, so use a cascading
method from a Auth object. so in the same session, user can use API for
different platforms if the Auth is set. Because we will have different
platforms (SBG US, SBG NCI cancer cloud and staging, other region) with
different API url. The auth is passing along the class, so even you sign a
children to a object, it has Auth with it to make sure you are using the
right authtoken and url. I am waiting to merge the branch soon.

> # example for upload_infoupload_info = function (auth_token = get_token(), upload_id = NULL) {
> 
> ```
> req = sbgapi(auth_token = auth_token,
>              path = paste0('upload/multipart/', upload_id),
>              method = 'GET')
> 
> status_check(req)
> ```
> 
> }
> - Explicit returns at the end of functions are superfluous (and
>   actually slower), so it is best to just return the object directly. The
>   only time you need an explicit return is when returning before the
>   function's end.if a parameter can take a enumerated number of values I
>   would suggest you use match.args() and a switch statement. This will
>   provide you with error checking of the arguments and partial matching, and
>   make the code more clear.
> 
> e.g.
> 
> sbgapi <- function(method = c('GET', 'POST', 'PUT', 'DELETE')) {
> 
> ```
> method <- match.args(method)
> 
> switch(method,
>   GET = {
>      GET()
>   },
>   POST = {
>     #validation code
>     POST()
>   }
> )
> ```
> 
> }

In addition for the sbgapi() function because every method returns a request

> response and the switch is the last statement in the function you don't
> need to
> save them to a variable at all, just use the implicit return from the
> switch.
> 
>    -
> 
>    A number of the files contained trailing whitespace characters
>    throughout the project. While these characters do not affect the
>    execution of
>    the code, they are unnecessary. You can use the following one liner to
>    strip them
>    out find . -type f -not -path './.git/*' -exec perl -i -pe 's/ +$//'
>    {} \;.
>    I would also suggest turning on visible whitespace in your editor of
>    choice
>    so you can easily spot this in the future.
>    -
> 
>    In file_meta_update() You use if (is.null(project_id) |
>    is.null(file_id)),
>    when doing logical comparisons of 1 element vectors it is better to
>    use ||
>    rather than the vectorized |.
> 
> Thank you again for the submission and your patience. Let me know if you
> have
> any further questions at (https://tracker.bioconductor.org/issue1264). I
> have
> cross posted this response to your GitHub Issue tracker for convenience
> (#15 https://github.com/road2stat/sbgr/issues/15).

These suggestions are very helpful! thanks so much Jim, we will check in
the update/fix once it's on svn.

In the future, we want to use github to develop the package mainly, but
link to bioc svn, any suggestion/guidance on this?

cheers

Tengfei

**Comment by jimhester** [comment] 2015-08-14 19:11
Tenfei,

Please make the suggested changes first (including the `easy_api` branch) and upload the updated tarball to https://tracker.bioconductor.org/issue1264.  I can do a brief review to verify things look good and then accept the package.

http://www.bioconductor.org/developers/how-to/git-mirrors/ contains documentation on using `git svn` to interact with the Bioconductor SVN repositories through git.

Jim

**Comment by tengfei** [comment] 2015-08-14 19:17
On Fri, Aug 14, 2015 at 3:11 PM, Jim Hester notifications@github.com
wrote:

> Tenfei,
> 
> Please make the suggested changes first (including the easy_api branch)
> and upload the updated tarball to
> https://tracker.bioconductor.org/issue1264. I can do a brief review to
> verify things look good and then accept the package.

Thanks, I will first merge to master on github, then upload the tarball
again, the problem is that  I don't have access to issue1264, Nan submitted
the package, can you add me "tengfei" to the issue as well?

Thanks

**Comment by nanxstats** [comment] 2015-08-17 10:30
@jimhester Thanks Jim! Your advice about the best coding practice is really great. Tengfei and me will discuss and make the suggested updates.

Nan

**Comment by tengfei** [comment] 2015-08-17 13:28
Hey Nan, when you have time, could you please make a tar ball based on
current merged version again, I updated according to Jim's suggestion, but
I still don't have permission to view the issue on tracker yet.

**Comment by jimhester** [comment] 2015-08-17 13:30
@tengfei, try now, I just added you to the nosy list (which should hopefully let you add a tarball as well)
https://tracker.bioconductor.org/issue1264

**Comment by tengfei** [comment] 2015-08-17 13:34
hi @jimhester still doesn't work, got the message "You are not allowed to view this page." ...

**Comment by jimhester** [comment] 2015-08-17 15:30
@tengfei it should work now, Dan manually added you to the issue, let me know if not!

**Comment by tengfei** [comment] 2015-08-17 15:47
@jimhester yes it works now! thanks a lot!

**Comment by tengfei** [comment] 2015-08-17 17:22
@jimhester 0.99.3 uploaded to tracker, please check, thanks again!

**Comment by tengfei** [comment] 2015-08-19 17:46
@jimhester 0.99.4 is uploaded to tracker too, that fix the potential R 3.1 compatible problem and Enum class importing problem.

**Comment by tengfei** [comment] 2015-08-20 15:02
@jimhester 0.99.5 submitted for review as well.

**Comment by tengfei** [comment] 2015-08-21 14:55
@jimhester hi jim, it would be nice and very helpful if we could have this on devel svn this week, so we could have a build next Monday or so. Please let me know if there is more issues, thanks again!

**Closed as completed** 2015-09-02 00:23 UTC
